[package]
name = "supercharged-dhbw"
version = "2.3.0"
entrypoint = "lib.typ"
authors = ["Danny Seidel <@DannySeidel>", "Thomas Gingele <b1tc0r3@proton.me>"]
license = "MIT"
description = "Unofficial Template for DHBW"
repository = "https://github.com/DannySeidel/typst-dhbw-template"
keywords = ["dhbw", "thesis"]
categories = ["paper", "thesis", "report"]
exclude = ["example.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
